/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_lutao_cmakejni_MainActivity */

#ifndef _Included_com_example_lutao_cmakejni_MainActivity
#define _Included_com_example_lutao_cmakejni_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_lutao_cmakejni_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_lutao_cmakejni_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_example_lutao_cmakejni_MainActivity
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_lutao_cmakejni_MainActivity_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_example_lutao_cmakejni_MainActivity
 * Method:    nativeFree
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_lutao_cmakejni_MainActivity_nativeFree
  (JNIEnv *, jobject);

/*
 * Class:     com_example_lutao_cmakejni_MainActivity
 * Method:    nativeWorker
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_lutao_cmakejni_MainActivity_nativeWorker
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_lutao_cmakejni_MainActivity
 * Method:    posixThreads
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_lutao_cmakejni_MainActivity_posixThreads
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
