/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_lutao_cmakejni_LocalEchoActivity */

#ifndef _Included_com_example_lutao_cmakejni_LocalEchoActivity
#define _Included_com_example_lutao_cmakejni_LocalEchoActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_lutao_cmakejni_LocalEchoActivity
 * Method:    nativeStartLocalServer
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_lutao_cmakejni_LocalEchoActivity_nativeStartLocalServer
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
